# netlify.toml

[build]
  publish = "."    # tu carpeta raíz con index.html

# 1) Excluir de la regla SPA todos los ficheros estáticos:
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
  # los paths que coincidan con estas extensiones NO se redirigen:
  conditions = { NotFile = true, NotPath = "/api/*" }

