[build]
  command = "npm run build"
  publish = "dist"

# Sirve el service worker real
[[redirects]]
  from   = "/service-worker.js"
  to     = "/service-worker.js"
  status = 200
  force  = true

# Sirve el manifest real
[[redirects]]
  from   = "/manifest.webmanifest"
  to     = "/manifest.webmanifest"
  status = 200
  force  = true

# Sirve los iconos reales
[[redirects]]
  from   = "/icons/*"
  to     = "/icons/:splat"
  status = 200
  force  = true

# Sirve los assets reales (js/css)
[[redirects]]
  from   = "/assets/*"
  to     = "/assets/:splat"
  status = 200
  force  = true

# Fallback SPA: todo lo demás va a index.html
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
