[build]
  command = "npm run build"
  publish = "dist"

# 1) Asegúrate de que los archivos estáticos bajo /assets se sirvan directamente
[[redirects]]
  from   = "/assets/*"
  to     = "/assets/:splat"
  status = 200

# 2) Fallback para tu SPA: cualquier otra ruta va a index.html
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
